export const TYPES = {
  CREATE_DATA: "CREATE_DATA",
  READ_ALL_DATA: "CREATE_DATA",
  READ_ONE_DATA: "READ_ONE_DATA",
  UPDATE_DATA: "READ_ONE_DATA",
  DELETE_DATA: "DELETE_DATA",
  NO_DATA: "NO_DATA",
};
